pantalla: 
 ancho: 800
 alto: 600

configuracion:
 vel_personaje: 4
 margen_scroll: 30

tipos: 
 - nombre: barraca
   imagen: img/dibujo_estatico/construcciones/barraks/barraks.png

 - nombre: soldado
   imagen: img/protagonista/spartan.png
   fps: 10
   delay: 5

 - nombre: wheel
   imagen: img/dibujo_dinamico/wheel.png
   fps: 6
   delay: 5

 - nombre: herreria
   imagen: img/dibujo_dinamico/mirador.png
   fps: 10
   delay: 5

 - nombre: pino
   imagen: img/dibujo_estatico/arbol/pinetree.png

 - nombre: church
   imagen: img/dibujo_estatico/construcciones/church.png

 - nombre: firestation
   imagen: img/dibujo_estatico/construcciones/firestation.png

 - nombre: arbol
   imagen: img/dibujo_estatico/arbol/firtree.png

escenario:
 nombre: orleans
 size_x: 100
 size_y: 100
 entidades: 
  - { x : 2, y: 1, tipo: pino }
  - { x : 2, y: 0, tipo: arbol }
  - { x : 6, y: 6, tipo: church }
  - { x : 4, y: 0, tipo: herreria }
  - { x : 4, y: 4, tipo: wheel }
  - { x : 3, y: 1, tipo: barraca }
  - { x : 3, y: 0, tipo: firestation }
 protagonista:
  - tipo: soldado
    x: 50
    y: 50
